// Code generated by mockery v1.0.0. DO NOT EDIT.

package gui

import mock "github.com/stretchr/testify/mock"

// mockScreenInterface is an autogenerated mock type for the screenInterface type
type mockScreenInterface struct {
	mock.Mock
}

// updateLabel provides a mock function with given fields: _a0
func (_m *mockScreenInterface) updateLabel(_a0 string) {
	_m.Called(_a0)
}

// updateProgessBar provides a mock function with given fields: _a0
func (_m *mockScreenInterface) updateProgessBar(_a0 float64) {
	_m.Called(_a0)
}
