// Code generated by mockery v1.0.0. DO NOT EDIT.

package gui

import mock "github.com/stretchr/testify/mock"

// MockScreenInterface is an autogenerated mock type for the ScreenInterface type
type MockScreenInterface struct {
	mock.Mock
}

// UpdateLabel provides a mock function with given fields: _a0
func (_m *MockScreenInterface) UpdateLabel(_a0 string) {
	_m.Called(_a0)
}

// UpdateProgessBar provides a mock function with given fields: _a0
func (_m *MockScreenInterface) UpdateProgessBar(_a0 float64) {
	_m.Called(_a0)
}
