name: Lint Revive
on:
  pull_request:
  push:
    paths:
      - '**.go'
      - 'revive.toml'
      - '.github/workflows/lint.yaml'

jobs:
  lint-revive:
    name: Lint Revive
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run Revive Action
      uses: docker://morphy/revive-action:v2
      with:
        config: revive.toml

    - name: Check formatting
      run: test -z $(gofmt -l .) || (gofmt -l . && exit 1)